"""analysis 端口协议（§3.1.3）：Repository / Stream / Publisher / Clock / 交易日历。

Redis Stream 与 Dramatiq 的具体 Adapter 位于 infrastructure/；
应用服务不得依赖 Redis/Dramatiq 客户端类型。
"""

from __future__ import annotations

import uuid
from datetime import date, datetime
from typing import Any, Protocol

from backend.shared.clock import Clock, SystemClock  # noqa: F401 - 统一出口

__all__ = ["Clock", "SystemClock"]


class AnalysisTaskRepository(Protocol):
    def add(self, task: Any) -> None: ...
    def get(self, task_id: uuid.UUID) -> Any | None: ...
    def get_by_idempotency_key(self, key: str) -> Any | None: ...
    def conditional_update(self, task_id: uuid.UUID, expect: dict, update: dict) -> bool: ...
    def list_by_statuses(self, statuses: set[str], *, limit: int, before: tuple[datetime, uuid.UUID] | None = None) -> list[Any]: ...
    def list_succeeded_with_unavailable_sections(self, *, limit: int) -> list[tuple[Any, Any]]: ...
    def list_recent_succeeded(self, *, limit: int) -> list[tuple[Any, Any]]: ...
    def find_expired_running(self, cutoff: datetime, *, limit: int = 100) -> list[Any]: ...
    def find_expired_cancel_requested(self, cutoff: datetime, *, limit: int = 100) -> list[Any]: ...


class TaskOutboxRepository(Protocol):
    def add(self, record: Any) -> None: ...
    def get(self, outbox_id: uuid.UUID) -> Any | None: ...
    def get_by_task_attempt(self, task_id: uuid.UUID, attempt_no: int) -> Any | None: ...
    def claim_due(self, now: datetime, *, limit: int, lease_seconds: int, lease_token: str) -> list[Any]: ...
    def conditional_update(self, outbox_id: uuid.UUID, expect: dict, update: dict) -> bool: ...
    def cancel_pending_for_task(self, task_id: uuid.UUID) -> int: ...


class AnalysisReportRepository(Protocol):
    def add(self, report: Any) -> None: ...
    def get_latest(self, task_id: uuid.UUID) -> Any | None: ...
    def next_version(self, task_id: uuid.UUID) -> int: ...


class TaskEventStreamPort(Protocol):
    """Redis Stream 适配（T4 实现）：仅六种业务事件持久化。"""

    def append(self, task_id: uuid.UUID, event_type: str, payload: dict) -> str: ...
    def read(self, task_id: uuid.UUID, after: str | None) -> list[tuple[str, str, dict]]: ...
    def trim(self, task_id: uuid.UUID) -> None: ...


class TaskMessagePublisherPort(Protocol):
    """Dramatiq Broker 适配（T4 实现）：只投递最小消息（task_id、attempt_no）。"""

    def publish(self, payload: dict) -> None: ...


class TradeDateCalendarPort(Protocol):
    """交易日历校正（T4 接入 AI.dataflows 交易日历）：返回有效交易日与校正说明。"""

    def correct(self, requested: date) -> tuple[date, str | None]: ...
